//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNoteMVC.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EID { get; set; }
        public string EName { get; set; }
        public string EEmail { get; set; }
        public string EMobile { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public Nullable<System.DateTime> Updatedate { get; set; }
    }
}
