//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNoteMVC.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usersubrole
    {
        public int SubRID { get; set; }
        public string Rolename { get; set; }
        public Nullable<int> URID { get; set; }
    
        public virtual UserRole UserRole { get; set; }
    }
}
